### ISSUE TITLE
Might no longer be needed

### ISSUE THREAD

**Issue by timendez** [audrenbdb/goforeground#1]
If anyone else stumbles across this, `robotgo` has 1st party support for the command:

```Go
robotgo.ActiveName("My Application Name")
```

It brings it to the foreground!

**Comment by audrenbdb** [comment]
There was a few pblem with robotgo:
- not working in our virtualized environment.
- annoying requirements.
- too heavy for such a small problem.

All in all, we wanted a lightweight package dedicated to this.
